apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app-deployment
  labels:
    app: hello-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-app
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        livenessProbe:
          httpGet:
            port: http-novo
            path: /
            scheme: HTTP
        readinessProbe:
          httpGet:
            port: http-novo
            path: /
            scheme: HTTP
        ports:
        - containerPort: 80
          name: http-novo
      - name: app
        image: emanuelflp/k8s-course:latest
        imagePullPolicy: Always
#        env:
#          - name: VARIAVEL_DIRETA
#            value: "DEFINI_DIRETAMENTE"
#          - name: VARIAVEL_DO_CONFIGMAP
#            valueFrom:
#              configMapKeyRef:
#                key: K8S_COURSE
#                name: nginx-configmap-envvars
#        envFrom:
#          - configMapRef:
#              name: nginx-configmap-envvars
#        volumeMounts:
#          - name: nginx-html
#            mountPath: /usr/share/nginx/html
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-configmap