apiVersion: v1
kind: Service
metadata:
  name: hello-app-service
spec:
  selector:
    app: hello-app
  ports:
    - port: 8080
      name: http
      targetPort: http-novo
      protocol: TCP
  type: NodePort