apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: hello-app-ingress
  labels:
    app: hello-app
spec:
  rules:
    - host: hello-app.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              serviceName: nginx-service
              servicePort: http
          - path: /login
            pathType: Prefix
            backend:
              serviceName: hello-app-service
              servicePort: http
  tls:
    - hosts:
        - hello-app.local
      secretName: certificado