apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-app-ingress
  labels:
    app: hello-app
spec:
  rules:
    - host: hello-app.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-service
                port:
                  name: http
          - path: /login
            pathType: Prefix
            backend:
              service:
                name: hello-app-service
                port:
                  name: http
  tls:
    - hosts:
        - hello-app.local
      secretName: certificado