apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gabriel-role
  namespace: default
rules:
  - verbs:
      - get
      - list
    resources:
      - pods
      - configmaps
    apiGroups:
      - ""
  - verbs:
      - get
    resources:
      - deployments
    apiGroups:
      - "apps"